# Generated by Django 4.2.8 on 2026-02-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_session_class_mode_session_proximity_radius_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_uuid',
            field=models.CharField(max_length=128),
        ),
    ]
